/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ladpa
 */
public class jfrmCalculadoraMejorada extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCalculadoraMejorada.class.getName());

    /**
     * Creates new form jfrmCalculadoraMejorada
     */         
        private String entrada="";
        private double numero1, numero2;
        private String operador;
        private boolean punto = true;
        private boolean continuar = true;
        private double acumulado;
        public jfrmCalculadoraMejorada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtn1 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtndecimal = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnporcent = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnraiz = new javax.swing.JButton();
        jbtnmulti = new javax.swing.JButton();
        jbtnsuma = new javax.swing.JButton();
        jbtnAC = new javax.swing.JButton();
        jbtnresult = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtnrest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn7.setText("7");
        jbtn7.addActionListener(this::jbtn7ActionPerformed);

        jbtn4.setText("4");
        jbtn4.addActionListener(this::jbtn4ActionPerformed);

        jtxtCantidad.setEnabled(false);
        jtxtCantidad.addActionListener(this::jtxtCantidadActionPerformed);

        jbtn1.setText("1");
        jbtn1.addActionListener(this::jbtn1ActionPerformed);

        jbtn0.setText("0");
        jbtn0.addActionListener(this::jbtn0ActionPerformed);

        jbtn8.setText("8");
        jbtn8.addActionListener(this::jbtn8ActionPerformed);

        jbtn5.setText("5");
        jbtn5.addActionListener(this::jbtn5ActionPerformed);

        jbtn2.setText("2");
        jbtn2.addActionListener(this::jbtn2ActionPerformed);

        jbtndecimal.setText(".");
        jbtndecimal.addActionListener(this::jbtndecimalActionPerformed);

        jbtn9.setText("9");
        jbtn9.addActionListener(this::jbtn9ActionPerformed);

        jbtnporcent.setText("%");
        jbtnporcent.addActionListener(this::jbtnporcentActionPerformed);

        jbtn6.setText("6");
        jbtn6.addActionListener(this::jbtn6ActionPerformed);

        jbtn3.setText("3");
        jbtn3.addActionListener(this::jbtn3ActionPerformed);

        jbtnC.setText("C");
        jbtnC.addActionListener(this::jbtnCActionPerformed);

        jbtnraiz.setText("√");
        jbtnraiz.addActionListener(this::jbtnraizActionPerformed);

        jbtnmulti.setText("*");
        jbtnmulti.addActionListener(this::jbtnmultiActionPerformed);

        jbtnsuma.setText("+");
        jbtnsuma.addActionListener(this::jbtnsumaActionPerformed);

        jbtnAC.setText("AC");
        jbtnAC.addActionListener(this::jbtnACActionPerformed);

        jbtnresult.setText("=");
        jbtnresult.addActionListener(this::jbtnresultActionPerformed);

        jbtndiv.setText("/");
        jbtndiv.addActionListener(this::jbtndivActionPerformed);

        jbtnrest.setText("-");
        jbtnrest.addActionListener(this::jbtnrestActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCantidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtndecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnporcent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnmulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnraiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtndiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtn7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtn0))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtn8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtn5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtn2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtndecimal)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnporcent)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnmulti)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnsuma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnraiz)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtndiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnrest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnresult)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:       
        entrada= entrada+7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtnrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "-";
        jtxtCantidad.setText(operador);
        punto = true;
    
    }//GEN-LAST:event_jbtnrestActionPerformed

    private void jbtnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "*";
        jtxtCantidad.setText(operador);
        punto = true;
    }//GEN-LAST:event_jbtnmultiActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "/";
        jtxtCantidad.setText(operador);
        punto = true;
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumaActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "+";
        jtxtCantidad.setText(operador);
        punto = true;
    }//GEN-LAST:event_jbtnsumaActionPerformed

    private void jbtnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnraizActionPerformed
        // TODO add your handling code here:
        operador = String.valueOf("√");
        entrada = "";
        jtxtCantidad.setText(operador);
        punto = true;  
    }//GEN-LAST:event_jbtnraizActionPerformed

    private void jbtnporcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnporcentActionPerformed
        // TODO add your handling code here:
        entrada = "";
        operador = "%";
        jtxtCantidad.setText(operador);
        punto = true;
    }//GEN-LAST:event_jbtnporcentActionPerformed

    private void jbtndecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndecimalActionPerformed
        // TODO add your handling code here:
        if (punto) {
            entrada = entrada + ".";
            jtxtCantidad.setText(entrada);
            punto = false;
        }                                        
    }//GEN-LAST:event_jbtndecimalActionPerformed

    private void jbtnresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresultActionPerformed
        // TODO add your handling code here:
    
        double resultado;
        numero2 = Double.parseDouble(entrada);
        jtxtCantidad.setText("");
        entrada = "";
        
        
        if (operador.equals("+")) {            
            resultado = numero1+numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            
        }
        else if (operador.equals("-")) {
            resultado = numero1-numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        else if (operador.equals("*")) {
            resultado = numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        else if (operador.equals("/")) {
            resultado = numero1/numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        else if (entrada.equals(0)) {
            resultado = numero1/numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        else if (operador.equals("√")) {
            if (numero2 >= 0) {
            resultado = Math.sqrt(numero2);
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            } else {
                jtxtCantidad.setText("Error");
            }  
        }
        
        else if (operador.equals("%")) {
            resultado = numero2/100;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnresultActionPerformed

    private void jbtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnACActionPerformed
        // TODO add your handling code here:
        entrada="";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnACActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
        String texto = jtxtCantidad.getText();

        if (texto.length() > 1) {
            texto = texto.substring(0, texto.length() - 1);
            entrada = texto;
            jtxtCantidad.setText(entrada);
        } else {
            entrada = "";
            jtxtCantidad.setText(entrada+"0");
        }
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:    
        entrada= entrada+8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalculadoraMejorada().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAC;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtndecimal;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtnmulti;
    private javax.swing.JButton jbtnporcent;
    private javax.swing.JButton jbtnraiz;
    private javax.swing.JButton jbtnrest;
    private javax.swing.JButton jbtnresult;
    private javax.swing.JButton jbtnsuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
